# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a354a9a0ccc773c5c352460356dff892713b7c8189c614639476f8b955724dab680e008830d91d6a9366cc09acfaa384360cd7f8cb0634542f154598572016db

test:
  secret_key_base: 484f0d39e447df4bc6c94c58d29aaa542e638d846611646ab3da134ca8e877de4e3c83ab5527c6280702b14823fcbf88b1b9c83a77a807e33a837e47e63b7312

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
